# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#

include:
  - board: seeeduino_xiao_ble
    shield: ZaruBall_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: ZaruBall_right rgbled_adapter
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_ZMK_LOGGING_MINIMAL=y -DCONFIG_ZARUBALL_INERTIAL_SCROLL_DEBUG=y
    artifact-name: ZaruBall_right_inertia_log
  - board: seeeduino_xiao_ble
    shield: settings_reset
